blank_issues_enabled: true
contact_links:
  - name: etalee Support
    url: https://t.me/ETALEE0
    about: Direct chat on non-inquiries subjects.
  - name: Channel
    url: https://t.me/ET_WO
    about: Documentation for getting started with bot.
